//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local time.
        /// </summary>
        public static string ClockDefaultName {
            get {
                return ResourceManager.GetString("ClockDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseItem {
            get {
                return ResourceManager.GetString("CloseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York.
        /// </summary>
        public static string DefaultLocation {
            get {
                return ResourceManager.GetString("DefaultLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of program has expired. Check http://htchome.org for newer version..
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open web page with forecast.
        /// </summary>
        public static string ForecastTooltip {
            get {
                return ResourceManager.GetString("ForecastTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to hide forecast.
        /// </summary>
        public static string HideForecastTooltip {
            get {
                return ResourceManager.GetString("HideForecastTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H:.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity:.
        /// </summary>
        public static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string JumpListCalendarWidget {
            get {
                return ResourceManager.GetString("JumpListCalendarWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FriendStream.
        /// </summary>
        public static string JumpListFriendStreamWidget {
            get {
                return ResourceManager.GetString("JumpListFriendStreamWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string JumpListNewsWidget {
            get {
                return ResourceManager.GetString("JumpListNewsWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string JumpListPhotosWidget {
            get {
                return ResourceManager.GetString("JumpListPhotosWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string JumpListWeatherWidget {
            get {
                return ResourceManager.GetString("JumpListWeatherWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string JumpListWidgets {
            get {
                return ResourceManager.GetString("JumpListWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        public static string Kmh {
            get {
                return ResourceManager.GetString("Kmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        public static string Mph {
            get {
                return ResourceManager.GetString("Mph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour time.
        /// </summary>
        public static string Options12H {
            get {
                return ResourceManager.GetString("Options12H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour time.
        /// </summary>
        public static string Options24H {
            get {
                return ResourceManager.GetString("Options24H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About HTC Home.
        /// </summary>
        public static string OptionsAboutHome {
            get {
                return ResourceManager.GetString("OptionsAboutHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string OptionsAboutTabHeader {
            get {
                return ResourceManager.GetString("OptionsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this widget.
        /// </summary>
        public static string OptionsAboutWidget {
            get {
                return ResourceManager.GetString("OptionsAboutWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string OptionsApplyButton {
            get {
                return ResourceManager.GetString("OptionsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you changing style widget will be automatically restarted after closing this window..
        /// </summary>
        public static string OptionsAutoRestart {
            get {
                return ResourceManager.GetString("OptionsAutoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start widget automatically when Windows starts.
        /// </summary>
        public static string OptionsAutostart {
            get {
                return ResourceManager.GetString("OptionsAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OptionsCancelButton {
            get {
                return ResourceManager.GetString("OptionsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you can&apos;t find your location try to choose another weather provider and search again..
        /// </summary>
        public static string OptionsCantFindCity {
            get {
                return ResourceManager.GetString("OptionsCantFindCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string OptionsCelsius {
            get {
                return ResourceManager.GetString("OptionsCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string OptionsCheckForUpdates {
            get {
                return ResourceManager.GetString("OptionsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check now.
        /// </summary>
        public static string OptionsCheckNow {
            get {
                return ResourceManager.GetString("OptionsCheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget style.
        /// </summary>
        public static string OptionsChooseStyle {
            get {
                return ResourceManager.GetString("OptionsChooseStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is protected by copyright law and distributed under Microsoft Public License..
        /// </summary>
        public static string OptionsCopyright {
            get {
                return ResourceManager.GetString("OptionsCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date display format:.
        /// </summary>
        public static string OptionsDateFormat {
            get {
                return ResourceManager.GetString("OptionsDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; time.
        /// </summary>
        public static string OptionsDateTime {
            get {
                return ResourceManager.GetString("OptionsDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version expires:.
        /// </summary>
        public static string OptionsExpiration {
            get {
                return ResourceManager.GetString("OptionsExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string OptionsExtrasDelete {
            get {
                return ResourceManager.GetString("OptionsExtrasDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this extra?.
        /// </summary>
        public static string OptionsExtrasDeleteMessage {
            get {
                return ResourceManager.GetString("OptionsExtrasDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string OptionsExtrasDeveloper {
            get {
                return ResourceManager.GetString("OptionsExtrasDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTC Home Extras are additional components that extends functionality of widgets. You can find available extras on our site..
        /// </summary>
        public static string OptionsExtrasInfo {
            get {
                return ResourceManager.GetString("OptionsExtrasInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install....
        /// </summary>
        public static string OptionsExtrasInstall {
            get {
                return ResourceManager.GetString("OptionsExtrasInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string OptionsExtrasTitle {
            get {
                return ResourceManager.GetString("OptionsExtrasTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsExtrasVersion {
            get {
                return ResourceManager.GetString("OptionsExtrasVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string OptionsFahrenheit {
            get {
                return ResourceManager.GetString("OptionsFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name for the first clock:.
        /// </summary>
        public static string OptionsFirstClockName {
            get {
                return ResourceManager.GetString("OptionsFirstClockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone for the first clock:.
        /// </summary>
        public static string OptionsFirstTimeZone {
            get {
                return ResourceManager.GetString("OptionsFirstTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionsGeneralTabHeader {
            get {
                return ResourceManager.GetString("OptionsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Extras:.
        /// </summary>
        public static string OptionsInstalledExtras {
            get {
                return ResourceManager.GetString("OptionsInstalledExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed updates.
        /// </summary>
        public static string OptionsInstalledUpdates {
            get {
                return ResourceManager.GetString("OptionsInstalledUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h..
        /// </summary>
        public static string OptionsIntervalHours {
            get {
                return ResourceManager.GetString("OptionsIntervalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        public static string OptionsIntervalMinutes {
            get {
                return ResourceManager.GetString("OptionsIntervalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsItem {
            get {
                return ResourceManager.GetString("OptionsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers per hour (km/h).
        /// </summary>
        public static string OptionsKmh {
            get {
                return ResourceManager.GetString("OptionsKmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionsLanguage {
            get {
                return ResourceManager.GetString("OptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTC Home is the set of widgets with HTC Sense style. &quot;HTC&quot; and &quot;HTC Sense&quot; are registered trademarks of HTC Corporation. HTC Home and htchome.org are not affiliated with HTC Corporation..
        /// </summary>
        public static string OptionsLegalInfo {
            get {
                return ResourceManager.GetString("OptionsLegalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        public static string OptionsLess {
            get {
                return ResourceManager.GetString("OptionsLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less checks.
        /// </summary>
        public static string OptionsLessChecks {
            get {
                return ResourceManager.GetString("OptionsLessChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less updates.
        /// </summary>
        public static string OptionsLessUpdates {
            get {
                return ResourceManager.GetString("OptionsLessUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string OptionsLocation {
            get {
                return ResourceManager.GetString("OptionsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string OptionsLocationWeatherTabHeader {
            get {
                return ResourceManager.GetString("OptionsLocationWeatherTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string OptionsMore {
            get {
                return ResourceManager.GetString("OptionsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More checks.
        /// </summary>
        public static string OptionsMoreChecks {
            get {
                return ResourceManager.GetString("OptionsMoreChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More updates.
        /// </summary>
        public static string OptionsMoreUpdates {
            get {
                return ResourceManager.GetString("OptionsMoreUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles per hour (mph).
        /// </summary>
        public static string OptionsMph {
            get {
                return ResourceManager.GetString("OptionsMph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters per second (m/s).
        /// </summary>
        public static string OptionsMs {
            get {
                return ResourceManager.GetString("OptionsMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OptionsOkButton {
            get {
                return ResourceManager.GetString("OptionsOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sounds when the weather is changing.
        /// </summary>
        public static string OptionsPlaySounds {
            get {
                return ResourceManager.GetString("OptionsPlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather providers gets weather data from different internet sources. They can differs by number of locations and provides different weather data..
        /// </summary>
        public static string OptionsProvidersInfo {
            get {
                return ResourceManager.GetString("OptionsProvidersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be applied after restarting the widget.
        /// </summary>
        public static string OptionsRestart {
            get {
                return ResourceManager.GetString("OptionsRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of your location.
        /// </summary>
        public static string OptionsSearchBox {
            get {
                return ResourceManager.GetString("OptionsSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name for the second clock:.
        /// </summary>
        public static string OptionsSecondClockName {
            get {
                return ResourceManager.GetString("OptionsSecondClockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone for the second clock:.
        /// </summary>
        public static string OptionsSecondTimeZone {
            get {
                return ResourceManager.GetString("OptionsSecondTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather provider:.
        /// </summary>
        public static string OptionsSelectProvider {
            get {
                return ResourceManager.GetString("OptionsSelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone:.
        /// </summary>
        public static string OptionsSelectTimeZone {
            get {
                return ResourceManager.GetString("OptionsSelectTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show additional information.
        /// </summary>
        public static string OptionsShowAdditionalInfo {
            get {
                return ResourceManager.GetString("OptionsShowAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show clock name.
        /// </summary>
        public static string OptionsShowClockName {
            get {
                return ResourceManager.GetString("OptionsShowClockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;feels like&quot; temperature instead of actual.
        /// </summary>
        public static string OptionsShowFeelsLike {
            get {
                return ResourceManager.GetString("OptionsShowFeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 4-day forecast.
        /// </summary>
        public static string OptionsShowForecast {
            get {
                return ResourceManager.GetString("OptionsShowForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show high and low temperature.
        /// </summary>
        public static string OptionsShowHighLow {
            get {
                return ResourceManager.GetString("OptionsShowHighLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string OptionsShowHumidity {
            get {
                return ResourceManager.GetString("OptionsShowHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icon on taskbar.
        /// </summary>
        public static string OptionsShowTaskbarIcon {
            get {
                return ResourceManager.GetString("OptionsShowTaskbarIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show temperature in:.
        /// </summary>
        public static string OptionsShowTempIn {
            get {
                return ResourceManager.GetString("OptionsShowTempIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show weather.
        /// </summary>
        public static string OptionsShowWeather {
            get {
                return ResourceManager.GetString("OptionsShowWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show weather animation.
        /// </summary>
        public static string OptionsShowWeatherAnimation {
            get {
                return ResourceManager.GetString("OptionsShowWeatherAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        public static string OptionsShowWindSpeed {
            get {
                return ResourceManager.GetString("OptionsShowWindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show wind speed in:.
        /// </summary>
        public static string OptionsShowWindSpeedIn {
            get {
                return ResourceManager.GetString("OptionsShowWindSpeedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install updates automatically without permission.
        /// </summary>
        public static string OptionsSilentUpdate {
            get {
                return ResourceManager.GetString("OptionsSilentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget size:.
        /// </summary>
        public static string OptionsSize {
            get {
                return ResourceManager.GetString("OptionsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larger.
        /// </summary>
        public static string OptionsSizeLarger {
            get {
                return ResourceManager.GetString("OptionsSizeLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller.
        /// </summary>
        public static string OptionsSizeSmaller {
            get {
                return ResourceManager.GetString("OptionsSizeSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin:.
        /// </summary>
        public static string OptionsSkin {
            get {
                return ResourceManager.GetString("OptionsSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string OptionsStartup {
            get {
                return ResourceManager.GetString("OptionsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string OptionsStyleTabHeader {
            get {
                return ResourceManager.GetString("OptionsStyleTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time display format:.
        /// </summary>
        public static string OptionsTimeFormat {
            get {
                return ResourceManager.GetString("OptionsTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget transparency:.
        /// </summary>
        public static string OptionsTransparency {
            get {
                return ResourceManager.GetString("OptionsTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of your clock:.
        /// </summary>
        public static string OptionsTypeClockName {
            get {
                return ResourceManager.GetString("OptionsTypeClockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string OptionsUI {
            get {
                return ResourceManager.GetString("OptionsUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update frequency:.
        /// </summary>
        public static string OptionsUpdateInterval {
            get {
                return ResourceManager.GetString("OptionsUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string OptionsUpdates {
            get {
                return ResourceManager.GetString("OptionsUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates can fix some errors or add new features. It&apos;s highly recommended to install all updates..
        /// </summary>
        public static string OptionsUpdatesInfo {
            get {
                return ResourceManager.GetString("OptionsUpdatesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Aero Glass effect.
        /// </summary>
        public static string OptionsUseAero {
            get {
                return ResourceManager.GetString("OptionsUseAero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use non-system time.
        /// </summary>
        public static string OptionsUseNonSystemTime {
            get {
                return ResourceManager.GetString("OptionsUseNonSystemTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsVersion {
            get {
                return ResourceManager.GetString("OptionsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string OptionsWeatherData {
            get {
                return ResourceManager.GetString("OptionsWeatherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather refresh interval:.
        /// </summary>
        public static string OptionsWeatherInterval {
            get {
                return ResourceManager.GetString("OptionsWeatherInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string OptionsWeatherScale {
            get {
                return ResourceManager.GetString("OptionsWeatherScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTC Home Options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup your location in settings.
        /// </summary>
        public static string SetupLocation {
            get {
                return ResourceManager.GetString("SetupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show forecast bar.
        /// </summary>
        public static string ShowForecast {
            get {
                return ResourceManager.GetString("ShowForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show forecast.
        /// </summary>
        public static string ShowForecastTooltip {
            get {
                return ResourceManager.GetString("ShowForecastTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on top of all windows.
        /// </summary>
        public static string TopMost {
            get {
                return ResourceManager.GetString("TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed:.
        /// </summary>
        public static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
    }
}
