//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTCHome.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        // Mugen fork: ApplicationSettingsBase supports SettingsKey specifically
        // for multiple independent instances of the same settings class. We use
        // --profile <id> to give every HTC Home host its own user settings while
        // keeping the legacy no-argument behavior fully compatible.
        public Settings() {
            string profileId = GetProfileId();
            global::HTCHome.Core.Environment.ProfileId = profileId;
            if (!string.IsNullOrEmpty(profileId)) {
                this.SettingsKey = profileId;

                // Resume diagnostic build: observe WPF's normal renderer. The
                // SoftwareOnly experiment changed the symptom but did not prevent
                // the post-hibernate DUCE/HwndTarget failure.
                global::HTCHome.ResumeDiagnostics.Start();
            }
        }

        private static string GetProfileId() {
            string[] args = global::System.Environment.GetCommandLineArgs();
            for (int i = 1; i < args.Length; i++) {
                string value = null;
                if (string.Equals(args[i], "--profile", global::System.StringComparison.OrdinalIgnoreCase) && i + 1 < args.Length) {
                    value = args[++i];
                }
                else if (args[i].StartsWith("--profile=", global::System.StringComparison.OrdinalIgnoreCase)) {
                    value = args[i].Substring("--profile=".Length);
                }

                if (!string.IsNullOrWhiteSpace(value)) {
                    return SanitizeProfileId(value);
                }
            }
            return string.Empty;
        }

        private static string SanitizeProfileId(string value) {
            var result = new global::System.Text.StringBuilder();
            foreach (char c in value.Trim()) {
                if (char.IsLetterOrDigit(c) || c == '-' || c == '_' || c == '.') {
                    result.Append(c);
                }
                else {
                    result.Append('_');
                }
                if (result.Length >= 64) break;
            }
            return result.ToString();
        }
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<ArrayOfString xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  <string>Weather/Clock widget</string>\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LoadedWidgets {
            get { return ((global::System.Collections.Specialized.StringCollection)(this["LoadedWidgets"])); }
            set { this["LoadedWidgets"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Locale {
            get { return ((string)(this["Locale"])); }
            set { this["Locale"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableGlass {
            get { return ((bool)(this["EnableGlass"])); }
            set { this["EnableGlass"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autostart {
            get { return ((bool)(this["Autostart"])); }
            set { this["Autostart"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableUpdates {
            get { return false; }
            set { this["EnableUpdates"] = false; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseProxy {
            get { return ((bool)(this["UseProxy"])); }
            set { this["UseProxy"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1")]
        public string ProxyAddress {
            get { return ((string)(this["ProxyAddress"])); }
            set { this["ProxyAddress"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProxyPort {
            get { return ((int)(this["ProxyPort"])); }
            set { this["ProxyPort"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Username")]
        public string ProxyUsername {
            get { return ((string)(this["ProxyUsername"])); }
            set { this["ProxyUsername"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password")]
        public string ProxyPassword {
            get { return ((string)(this["ProxyPassword"])); }
            set { this["ProxyPassword"] = value; }
        }
    }
}

namespace HTCHome
{
    // Passive diagnostics for the long-standing WPF hibernate/resume failure.
    // This class deliberately does not move, redraw, recreate, close or restart
    // any window. It only records the native event sequence and process/window
    // state around resume so that a later DUCE/HwndTarget failure can be tied to
    // what Windows and DWM actually did immediately beforehand.
    internal static class ResumeDiagnostics
    {
        private const int WM_WINDOWPOSCHANGING = 0x0046;
        private const int WM_WINDOWPOSCHANGED = 0x0047;
        private const int WM_DISPLAYCHANGE = 0x007E;
        private const int WM_POWERBROADCAST = 0x0218;
        private const int WM_DEVICECHANGE = 0x0219;
        private const int WM_DPICHANGED = 0x02E0;
        private const int WM_DWMCOMPOSITIONCHANGED = 0x031E;

        private const int PBT_APMSUSPEND = 0x0004;
        private const int PBT_APMRESUMESUSPEND = 0x0007;
        private const int PBT_APMRESUMEAUTOMATIC = 0x0012;

        private static readonly object Sync = new object();
        private static bool started;
        private static global::System.DateTime traceUntilUtc = global::System.DateTime.MinValue;
        private static int traceMessageCount;
        private const int MaxWindowPositionMessagesPerResume = 250;

        [global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        private struct WINDOWPOS
        {
            public global::System.IntPtr hwnd;
            public global::System.IntPtr hwndInsertAfter;
            public int x;
            public int y;
            public int cx;
            public int cy;
            public uint flags;
        }

        public static void Start()
        {
            lock (Sync)
            {
                if (started)
                    return;
                started = true;
            }

            try
            {
                global::Microsoft.Win32.SystemEvents.PowerModeChanged += SystemEvents_PowerModeChanged;
                global::Microsoft.Win32.SystemEvents.DisplaySettingsChanging += SystemEvents_DisplaySettingsChanging;
                global::Microsoft.Win32.SystemEvents.DisplaySettingsChanged += SystemEvents_DisplaySettingsChanged;
                global::System.Windows.Interop.ComponentDispatcher.ThreadFilterMessage += ComponentDispatcher_ThreadFilterMessage;
                SafeLog("[ResumeDiag] START pid=" + global::System.Diagnostics.Process.GetCurrentProcess().Id +
                    " renderMode=" + global::System.Windows.Media.RenderOptions.ProcessRenderMode +
                    " tier=" + (global::System.Windows.Media.RenderCapability.Tier >> 16));
            }
            catch (global::System.Exception ex)
            {
                SafeLog("[ResumeDiag] START failed: " + ex.GetType().FullName + ": " + ex.Message);
            }
        }

        private static void SystemEvents_PowerModeChanged(object sender, global::Microsoft.Win32.PowerModeChangedEventArgs e)
        {
            SafeLog("[ResumeDiag] SystemEvents.PowerModeChanged mode=" + e.Mode);

            if (e.Mode == global::Microsoft.Win32.PowerModes.Suspend)
            {
                SnapshotOnUi("systemevents-suspend");
            }
            else if (e.Mode == global::Microsoft.Win32.PowerModes.Resume)
            {
                BeginResumeTrace("systemevents-resume");
            }
        }

        private static void SystemEvents_DisplaySettingsChanging(object sender, global::System.EventArgs e)
        {
            SafeLog("[ResumeDiag] SystemEvents.DisplaySettingsChanging");
            SnapshotOnUi("display-settings-changing");
        }

        private static void SystemEvents_DisplaySettingsChanged(object sender, global::System.EventArgs e)
        {
            SafeLog("[ResumeDiag] SystemEvents.DisplaySettingsChanged");
            SnapshotOnUi("display-settings-changed");
        }

        private static void ComponentDispatcher_ThreadFilterMessage(ref global::System.Windows.Interop.MSG msg, ref bool handled)
        {
            try
            {
                int message = msg.message;
                if (message == WM_POWERBROADCAST)
                {
                    long wParam = msg.wParam.ToInt64();
                    SafeLog("[ResumeDiag] WM_POWERBROADCAST hwnd=0x" + msg.hwnd.ToInt64().ToString("X") +
                        " wParam=0x" + wParam.ToString("X") + " (" + PowerBroadcastName(wParam) + ")");

                    if (wParam == PBT_APMRESUMESUSPEND || wParam == PBT_APMRESUMEAUTOMATIC)
                        BeginResumeTrace("wm-powerbroadcast-" + PowerBroadcastName(wParam));
                    else if (wParam == PBT_APMSUSPEND)
                        SnapshotOnUi("wm-powerbroadcast-suspend");
                    return;
                }

                if (message == WM_DISPLAYCHANGE || message == WM_DEVICECHANGE ||
                    message == WM_DWMCOMPOSITIONCHANGED || message == WM_DPICHANGED)
                {
                    SafeLog("[ResumeDiag] " + MessageName(message) +
                        " hwnd=0x" + msg.hwnd.ToInt64().ToString("X") +
                        " wParam=0x" + msg.wParam.ToInt64().ToString("X") +
                        " lParam=0x" + msg.lParam.ToInt64().ToString("X"));
                    SnapshotOnUi("native-" + MessageName(message));
                    return;
                }

                if ((message == WM_WINDOWPOSCHANGING || message == WM_WINDOWPOSCHANGED) && IsResumeTraceActive())
                {
                    if (global::System.Threading.Interlocked.Increment(ref traceMessageCount) <= MaxWindowPositionMessagesPerResume)
                    {
                        string details = "";
                        if (msg.lParam != global::System.IntPtr.Zero)
                        {
                            WINDOWPOS pos = (WINDOWPOS)global::System.Runtime.InteropServices.Marshal.PtrToStructure(
                                msg.lParam, typeof(WINDOWPOS));
                            details = " target=0x" + pos.hwnd.ToInt64().ToString("X") +
                                " x=" + pos.x + " y=" + pos.y + " cx=" + pos.cx + " cy=" + pos.cy +
                                " flags=0x" + pos.flags.ToString("X");
                        }
                        SafeLog("[ResumeDiag] " + MessageName(message) +
                            " msgHwnd=0x" + msg.hwnd.ToInt64().ToString("X") + details);
                    }
                }
            }
            catch (global::System.Exception ex)
            {
                SafeLog("[ResumeDiag] native-message parse failed: " + ex.GetType().FullName + ": " + ex.Message);
            }
        }

        private static void BeginResumeTrace(string reason)
        {
            traceUntilUtc = global::System.DateTime.UtcNow.AddSeconds(30);
            global::System.Threading.Interlocked.Exchange(ref traceMessageCount, 0);
            SafeLog("[ResumeDiag] RESUME TRACE BEGIN reason=" + reason + " window=30s");

            ScheduleSnapshot(0, reason + "+0ms");
            ScheduleSnapshot(250, reason + "+250ms");
            ScheduleSnapshot(1000, reason + "+1s");
            ScheduleSnapshot(3000, reason + "+3s");
            ScheduleSnapshot(10000, reason + "+10s");
            ScheduleSnapshot(30000, reason + "+30s");
        }

        private static bool IsResumeTraceActive()
        {
            return global::System.DateTime.UtcNow <= traceUntilUtc;
        }

        private static void ScheduleSnapshot(int delayMs, string reason)
        {
            try
            {
                global::System.Windows.Application app = global::System.Windows.Application.Current;
                if (app == null || app.Dispatcher == null)
                    return;

                app.Dispatcher.BeginInvoke(new global::System.Action(delegate
                {
                    if (delayMs <= 0)
                    {
                        Snapshot(reason);
                        return;
                    }

                    global::System.Windows.Threading.DispatcherTimer timer = new global::System.Windows.Threading.DispatcherTimer();
                    timer.Interval = global::System.TimeSpan.FromMilliseconds(delayMs);
                    timer.Tick += delegate(object sender, global::System.EventArgs e)
                    {
                        timer.Stop();
                        Snapshot(reason);
                    };
                    timer.Start();
                }));
            }
            catch (global::System.Exception ex)
            {
                SafeLog("[ResumeDiag] ScheduleSnapshot failed: " + ex.GetType().FullName + ": " + ex.Message);
            }
        }

        private static void SnapshotOnUi(string reason)
        {
            ScheduleSnapshot(0, reason);
        }

        private static void Snapshot(string reason)
        {
            try
            {
                global::System.Diagnostics.Process process = global::System.Diagnostics.Process.GetCurrentProcess();
                process.Refresh();

                SafeLog("[ResumeDiag] SNAPSHOT reason=" + reason +
                    " pid=" + process.Id +
                    " handles=" + process.HandleCount +
                    " workingMB=" + Mb(process.WorkingSet64) +
                    " privateMB=" + Mb(process.PrivateMemorySize64) +
                    " managedMB=" + Mb(global::System.GC.GetTotalMemory(false)) +
                    " renderMode=" + global::System.Windows.Media.RenderOptions.ProcessRenderMode +
                    " tier=" + (global::System.Windows.Media.RenderCapability.Tier >> 16));

                global::System.Windows.Application app = global::System.Windows.Application.Current;
                if (app == null)
                {
                    SafeLog("[ResumeDiag] WINDOWS application=null");
                    return;
                }

                int index = 0;
                foreach (global::System.Windows.Window window in app.Windows)
                {
                    global::System.IntPtr hwnd = new global::System.Windows.Interop.WindowInteropHelper(window).Handle;
                    string monitor = "n/a";
                    string bounds = "n/a";
                    try
                    {
                        global::System.Windows.Forms.Screen screen = global::System.Windows.Forms.Screen.FromHandle(hwnd);
                        if (screen != null)
                        {
                            monitor = screen.DeviceName;
                            bounds = screen.Bounds.Left + "," + screen.Bounds.Top + "," +
                                screen.Bounds.Width + "x" + screen.Bounds.Height +
                                (screen.Primary ? ",primary" : "");
                        }
                    }
                    catch { }

                    SafeLog("[ResumeDiag] WINDOW #" + index +
                        " type=" + window.GetType().FullName +
                        " hwnd=0x" + hwnd.ToInt64().ToString("X") +
                        " visible=" + window.IsVisible +
                        " active=" + window.IsActive +
                        " state=" + window.WindowState +
                        " topmost=" + window.Topmost +
                        " left=" + FormatDouble(window.Left) +
                        " top=" + FormatDouble(window.Top) +
                        " width=" + FormatDouble(window.Width) +
                        " height=" + FormatDouble(window.Height) +
                        " actual=" + FormatDouble(window.ActualWidth) + "x" + FormatDouble(window.ActualHeight) +
                        " monitor=" + monitor +
                        " bounds=" + bounds);
                    index++;
                }
            }
            catch (global::System.Exception ex)
            {
                SafeLog("[ResumeDiag] SNAPSHOT failed reason=" + reason + ": " + ex.GetType().FullName + ": " + ex.Message);
            }
        }

        private static string PowerBroadcastName(long value)
        {
            if (value == PBT_APMSUSPEND) return "PBT_APMSUSPEND";
            if (value == PBT_APMRESUMESUSPEND) return "PBT_APMRESUMESUSPEND";
            if (value == PBT_APMRESUMEAUTOMATIC) return "PBT_APMRESUMEAUTOMATIC";
            return "unknown";
        }

        private static string MessageName(int message)
        {
            switch (message)
            {
                case WM_WINDOWPOSCHANGING: return "WM_WINDOWPOSCHANGING";
                case WM_WINDOWPOSCHANGED: return "WM_WINDOWPOSCHANGED";
                case WM_DISPLAYCHANGE: return "WM_DISPLAYCHANGE";
                case WM_POWERBROADCAST: return "WM_POWERBROADCAST";
                case WM_DEVICECHANGE: return "WM_DEVICECHANGE";
                case WM_DPICHANGED: return "WM_DPICHANGED";
                case WM_DWMCOMPOSITIONCHANGED: return "WM_DWMCOMPOSITIONCHANGED";
                default: return "WM_0x" + message.ToString("X");
            }
        }

        private static string Mb(long bytes)
        {
            return (bytes / 1024d / 1024d).ToString("0.0", global::System.Globalization.CultureInfo.InvariantCulture);
        }

        private static string FormatDouble(double value)
        {
            return value.ToString("0.##", global::System.Globalization.CultureInfo.InvariantCulture);
        }

        private static void SafeLog(string message)
        {
            try
            {
                global::HTCHome.App.Log(message);
            }
            catch
            {
                // Diagnostics must never change application behaviour.
            }
        }
    }
}
