//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTCHome.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        // Mugen fork: ApplicationSettingsBase supports SettingsKey specifically
        // for multiple independent instances of the same settings class. We use
        // --profile <id> to give every HTC Home host its own user settings while
        // keeping the legacy no-argument behavior fully compatible.
        public Settings() {
            string profileId = GetProfileId();
            global::HTCHome.Core.Environment.ProfileId = profileId;
            if (!string.IsNullOrEmpty(profileId)) {
                this.SettingsKey = profileId;

                // The classic WPF compositor can lose its DirectX render channel
                // across hibernate/resume on some multi-monitor systems and then
                // surface the failure as OutOfMemoryException from DUCE.SyncFlush.
                // Keep this workaround local to Mugen profile processes instead of
                // changing the machine-wide Avalon.Graphics registry setting.
                global::System.Windows.Media.RenderOptions.ProcessRenderMode =
                    global::System.Windows.Interop.RenderMode.SoftwareOnly;
            }
        }

        private static string GetProfileId() {
            string[] args = global::System.Environment.GetCommandLineArgs();
            for (int i = 1; i < args.Length; i++) {
                string value = null;
                if (string.Equals(args[i], "--profile", global::System.StringComparison.OrdinalIgnoreCase) && i + 1 < args.Length) {
                    value = args[++i];
                }
                else if (args[i].StartsWith("--profile=", global::System.StringComparison.OrdinalIgnoreCase)) {
                    value = args[i].Substring("--profile=".Length);
                }

                if (!string.IsNullOrWhiteSpace(value)) {
                    return SanitizeProfileId(value);
                }
            }
            return string.Empty;
        }

        private static string SanitizeProfileId(string value) {
            var result = new global::System.Text.StringBuilder();
            foreach (char c in value.Trim()) {
                if (char.IsLetterOrDigit(c) || c == '-' || c == '_' || c == '.') {
                    result.Append(c);
                }
                else {
                    result.Append('_');
                }
                if (result.Length >= 64) break;
            }
            return result.ToString();
        }
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<ArrayOfString xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  <string>Weather/Clock widget</string>\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LoadedWidgets {
            get { return ((global::System.Collections.Specialized.StringCollection)(this["LoadedWidgets"])); }
            set { this["LoadedWidgets"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Locale {
            get { return ((string)(this["Locale"])); }
            set { this["Locale"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableGlass {
            get { return ((bool)(this["EnableGlass"])); }
            set { this["EnableGlass"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autostart {
            get { return ((bool)(this["Autostart"])); }
            set { this["Autostart"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableUpdates {
            get { return false; }
            set { this["EnableUpdates"] = false; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseProxy {
            get { return ((bool)(this["UseProxy"])); }
            set { this["UseProxy"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1")]
        public string ProxyAddress {
            get { return ((string)(this["ProxyAddress"])); }
            set { this["ProxyAddress"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProxyPort {
            get { return ((int)(this["ProxyPort"])); }
            set { this["ProxyPort"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Username")]
        public string ProxyUsername {
            get { return ((string)(this["ProxyUsername"])); }
            set { this["ProxyUsername"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password")]
        public string ProxyPassword {
            get { return ((string)(this["ProxyPassword"])); }
            set { this["ProxyPassword"] = value; }
        }
    }
}
