//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendStream.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FriendStream.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearItem {
            get {
                return ResourceManager.GetString("ClearItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseItem {
            get {
                return ResourceManager.GetString("CloseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of program has expired. Check http://htchome.org for newer version..
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string JumpListCalendarWidget {
            get {
                return ResourceManager.GetString("JumpListCalendarWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string JumpListClockWidget {
            get {
                return ResourceManager.GetString("JumpListClockWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string JumpListNewsWidget {
            get {
                return ResourceManager.GetString("JumpListNewsWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string JumpListPhotosWidget {
            get {
                return ResourceManager.GetString("JumpListPhotosWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string JumpListWeatherWidget {
            get {
                return ResourceManager.GetString("JumpListWeatherWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string JumpListWidgets {
            get {
                return ResourceManager.GetString("JumpListWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to likes this.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About HTC Home.
        /// </summary>
        public static string OptionsAboutHome {
            get {
                return ResourceManager.GetString("OptionsAboutHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string OptionsAboutTabHeader {
            get {
                return ResourceManager.GetString("OptionsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this widget.
        /// </summary>
        public static string OptionsAboutWidget {
            get {
                return ResourceManager.GetString("OptionsAboutWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string OptionsApplyButton {
            get {
                return ResourceManager.GetString("OptionsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you changing style widget will be automatically restarted after closing this window..
        /// </summary>
        public static string OptionsAutoRestart {
            get {
                return ResourceManager.GetString("OptionsAutoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start widget automatically when Windows starts.
        /// </summary>
        public static string OptionsAutostart {
            get {
                return ResourceManager.GetString("OptionsAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch pictures automatically.
        /// </summary>
        public static string OptionsAutoSwitch {
            get {
                return ResourceManager.GetString("OptionsAutoSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OptionsCancelButton {
            get {
                return ResourceManager.GetString("OptionsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        public static string OptionsChange {
            get {
                return ResourceManager.GetString("OptionsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string OptionsCheckForUpdates {
            get {
                return ResourceManager.GetString("OptionsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check now.
        /// </summary>
        public static string OptionsCheckNow {
            get {
                return ResourceManager.GetString("OptionsCheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget style.
        /// </summary>
        public static string OptionsChooseStyle {
            get {
                return ResourceManager.GetString("OptionsChooseStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is protected by copyright law and distributed under Microsoft Public License..
        /// </summary>
        public static string OptionsCopyright {
            get {
                return ResourceManager.GetString("OptionsCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version expires:.
        /// </summary>
        public static string OptionsExpiration {
            get {
                return ResourceManager.GetString("OptionsExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string OptionsExtrasDelete {
            get {
                return ResourceManager.GetString("OptionsExtrasDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this extra?.
        /// </summary>
        public static string OptionsExtrasDeleteMessage {
            get {
                return ResourceManager.GetString("OptionsExtrasDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string OptionsExtrasDeveloper {
            get {
                return ResourceManager.GetString("OptionsExtrasDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTC Home Extras are additional components that extends functionality of widgets. You can find available extras on our site..
        /// </summary>
        public static string OptionsExtrasInfo {
            get {
                return ResourceManager.GetString("OptionsExtrasInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install....
        /// </summary>
        public static string OptionsExtrasInstall {
            get {
                return ResourceManager.GetString("OptionsExtrasInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string OptionsExtrasTitle {
            get {
                return ResourceManager.GetString("OptionsExtrasTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsExtrasVersion {
            get {
                return ResourceManager.GetString("OptionsExtrasVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionsGeneralTabHeader {
            get {
                return ResourceManager.GetString("OptionsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Extras:.
        /// </summary>
        public static string OptionsInstalledExtras {
            get {
                return ResourceManager.GetString("OptionsInstalledExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed updates.
        /// </summary>
        public static string OptionsInstalledUpdates {
            get {
                return ResourceManager.GetString("OptionsInstalledUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        public static string OptionsIntervalMinutes {
            get {
                return ResourceManager.GetString("OptionsIntervalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsItem {
            get {
                return ResourceManager.GetString("OptionsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionsLanguage {
            get {
                return ResourceManager.GetString("OptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTC Home is the set of widgets with HTC Sense style. &quot;HTC&quot; and &quot;HTC Sense&quot; are registered trademarks of HTC Corporation. HTC Home and htchome.org are not affiliated with HTC Corporation..
        /// </summary>
        public static string OptionsLegalInfo {
            get {
                return ResourceManager.GetString("OptionsLegalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        public static string OptionsLess {
            get {
                return ResourceManager.GetString("OptionsLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less checks.
        /// </summary>
        public static string OptionsLessChecks {
            get {
                return ResourceManager.GetString("OptionsLessChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string OptionsMore {
            get {
                return ResourceManager.GetString("OptionsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More checks.
        /// </summary>
        public static string OptionsMoreChecks {
            get {
                return ResourceManager.GetString("OptionsMoreChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OptionsOkButton {
            get {
                return ResourceManager.GetString("OptionsOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures folder:.
        /// </summary>
        public static string OptionsPicsPath {
            get {
                return ResourceManager.GetString("OptionsPicsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh frequency:.
        /// </summary>
        public static string OptionsRefreshFreq {
            get {
                return ResourceManager.GetString("OptionsRefreshFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be applied after restarting the widget.
        /// </summary>
        public static string OptionsRestart {
            get {
                return ResourceManager.GetString("OptionsRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation angle:.
        /// </summary>
        public static string OptionsRotationAngle {
            get {
                return ResourceManager.GetString("OptionsRotationAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icon on taskbar.
        /// </summary>
        public static string OptionsShowTaskbarIcon {
            get {
                return ResourceManager.GetString("OptionsShowTaskbarIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install updates automatically without permission.
        /// </summary>
        public static string OptionsSilentUpdate {
            get {
                return ResourceManager.GetString("OptionsSilentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget size:.
        /// </summary>
        public static string OptionsSize {
            get {
                return ResourceManager.GetString("OptionsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larger.
        /// </summary>
        public static string OptionsSizeLarger {
            get {
                return ResourceManager.GetString("OptionsSizeLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller.
        /// </summary>
        public static string OptionsSizeSmaller {
            get {
                return ResourceManager.GetString("OptionsSizeSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string OptionsSocial {
            get {
                return ResourceManager.GetString("OptionsSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string OptionsStartup {
            get {
                return ResourceManager.GetString("OptionsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string OptionsStyleTabHeader {
            get {
                return ResourceManager.GetString("OptionsStyleTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures switching interval:.
        /// </summary>
        public static string OptionsSwitchInterval {
            get {
                return ResourceManager.GetString("OptionsSwitchInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        public static string OptionsSwitchIntervalLess {
            get {
                return ResourceManager.GetString("OptionsSwitchIntervalLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string OptionsSwitchIntervalMore {
            get {
                return ResourceManager.GetString("OptionsSwitchIntervalMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch pictures randomly.
        /// </summary>
        public static string OptionsSwitchRandom {
            get {
                return ResourceManager.GetString("OptionsSwitchRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget transparency:.
        /// </summary>
        public static string OptionsTransparency {
            get {
                return ResourceManager.GetString("OptionsTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        public static string OptionsTransparencyLess {
            get {
                return ResourceManager.GetString("OptionsTransparencyLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string OptionsTransparencyMore {
            get {
                return ResourceManager.GetString("OptionsTransparencyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string OptionsUI {
            get {
                return ResourceManager.GetString("OptionsUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update frequency:.
        /// </summary>
        public static string OptionsUpdateInterval {
            get {
                return ResourceManager.GetString("OptionsUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string OptionsUpdates {
            get {
                return ResourceManager.GetString("OptionsUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates can fix some errors or add new features. It&apos;s highly recommended to install all updates..
        /// </summary>
        public static string OptionsUpdatesInfo {
            get {
                return ResourceManager.GetString("OptionsUpdatesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsVersion {
            get {
                return ResourceManager.GetString("OptionsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTC Home Options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refreshing....
        /// </summary>
        public static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshItem {
            get {
                return ResourceManager.GetString("RefreshItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set image as desktop background.
        /// </summary>
        public static string SetAsWallpaperItem {
            get {
                return ResourceManager.GetString("SetAsWallpaperItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s on your mind?.
        /// </summary>
        public static string StatusTip {
            get {
                return ResourceManager.GetString("StatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on top of all windows.
        /// </summary>
        public static string TopMost {
            get {
                return ResourceManager.GetString("TopMost", resourceCulture);
            }
        }
    }
}
