<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Version>2.2.15</Version>
    <Authors>Stealth</Authors>
    <Copyright>© Stealth 2025</Copyright>
    <Product>MSN weather provider</Product>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\..\bin\Debug\Extras\Weather\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\..\..\bin\Release\Extras\Weather\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="msn.ext.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4">
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets></IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Home.Base\Home.Base.csproj">
      <ExcludeAssets>all</ExcludeAssets>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Weather.Base\Weather.Base.csproj">
      <ExcludeAssets>all</ExcludeAssets>
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>